# The Docker image that will be used to build your app
image: ubuntu:latest
# Functions that should be executed before the build script is run
before_script:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get -y install python3-pip python3-sphinx python3-sphinx-rtd-theme
  - pip3 install --no-input typing_extensions pyRDF numpy scikit-learn toml
pages:
  script:
    - cp pyproject.toml docs/
    - cd docs/ && docroot=`mktemp -d` && sphinx-build -M html source/ docroot/ && mv docroot/html/ ../public && cd -
    - touch .nojekyll
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
